server:
  name: go-location
  port: 8080

mongo:
  uri: mongodb://@localhost:27017
  database: location

sql:
  uri: devadmin:abcd1234@/masterdata?charset=utf8&parseTime=True&loc=Local

log:
  level: debug
  field_map:
    time: "@timestamp"
    msg: message

middleware_log:
  single: true
  status: status
  bytes: bytes
  request: request
  response: response
